/**
 * Generates road-following geometry for each MyBus route by routing through
 * its ordered stops with the public OSRM server, and writes
 * src/data/generated/mybus-geometry.ts. Falls back to straight stop-to-stop
 * lines for any route OSRM can't resolve. Run: npx tsx scripts/build-mybus-geometry.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { myBusRoutes } from "../src/data/mybus-routes";
import { myBusStops } from "../src/data/mybus-stops";

const OUT = join(__dirname, "..", "src", "data", "generated", "mybus-geometry.ts");
const OSRM = "https://router.project-osrm.org/route/v1/driving";

const coordOf = new Map(myBusStops.map((s) => [s.id, [s.lng, s.lat] as const]));
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const round = (n: number) => Number(n.toFixed(5));

async function geometryFor(stopIds: string[]): Promise<[number, number][]> {
  const points = stopIds.map((id) => coordOf.get(id)!);
  const straight = points.map(([lng, lat]) => [round(lng), round(lat)] as [number, number]);
  const path = points.map(([lng, lat]) => `${lng},${lat}`).join(";");
  try {
    const res = await fetch(
      `${OSRM}/${path}?overview=simplified&geometries=geojson`,
      { headers: { "User-Agent": "komyut-ta-bai/0.1 (transit research)" } }
    );
    const json = (await res.json()) as {
      code: string;
      routes?: { geometry: { coordinates: [number, number][] } }[];
    };
    if (json.code !== "Ok" || !json.routes?.[0]) {
      console.warn(`  OSRM ${json.code} — using straight line`);
      return straight;
    }
    return json.routes[0].geometry.coordinates.map(
      ([lng, lat]) => [round(lng), round(lat)] as [number, number]
    );
  } catch (error) {
    console.warn(`  OSRM error (${String(error)}) — using straight line`);
    return straight;
  }
}

async function main() {
  const geometry: Record<string, [number, number][]> = {};
  for (const route of myBusRoutes) {
    const ids = route.stops
      .slice()
      .sort((a, b) => a.sequence - b.sequence)
      .map((s) => s.stop_id);
    const coords = await geometryFor(ids);
    geometry[route.id] = coords;
    console.log(`${route.id}: ${coords.length} points`);
    await sleep(1200); // be polite to the public OSRM server
  }

  mkdirSync(join(__dirname, "..", "src", "data", "generated"), { recursive: true });
  writeFileSync(
    OUT,
    `// GENERATED by scripts/build-mybus-geometry.ts — do not edit by hand.\n` +
      `// Road-following polylines per MyBus route, via OSRM over OSM roads.\n\n` +
      `export const myBusGeometry: Record<string, [number, number][]> = ${JSON.stringify(
        geometry
      )};\n`
  );
  console.log(`\nWrote ${Object.keys(geometry).length} route geometries.`);
}

main();
